"""Lifecycle tools — project init, config, status."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml

from ..config import load_config, get_output_dir, get_project_dir, get_transcripts_dir, get_participant
from ..errors import validation_error, config_invalid
from ..sandbox import resolve_safe
from ..state import PipelineState


def detect_speakers(docx_path: str) -> dict[str, Any]:
    """Scan a .docx transcript and return detected speaker names with turn counts."""
    import docx

    path = Path(docx_path)
    if not path.exists():
        return {"error": {"message": f"File not found: {docx_path}"}}

    try:
        doc = docx.Document(str(path))
    except Exception as e:
        return {"error": {"message": f"Cannot open docx: {e}"}}

    timestamp_re = re.compile(r"^\d{1,2}:\d{2}\s*[-\u2013]\s*\d{1,2}:\d{2}$")
    speakers: dict[str, int] = {}
    paragraphs = [p.text.strip() for p in doc.paragraphs if p.text.strip()]

    i = 0
    while i < len(paragraphs) - 1:
        if i + 1 < len(paragraphs) and timestamp_re.match(paragraphs[i + 1]):
            speaker = paragraphs[i]
            speakers[speaker] = speakers.get(speaker, 0) + 1
            i += 3
        else:
            i += 1

    return {
        "file": path.name,
        "speakers": speakers,
        "total_turns": sum(speakers.values()),
    }


_GROUNDING_STUBS = {
    "focus_memo.md": (
        "# Focus Memo\n\n"
        "> Generated by uxr-grounding (Mode 0). Edit Researcher POV sections as needed.\n\n"
        "## Domain\n\n[Terms and phrases that capture the study domain]\n\n"
        "## Project Summary\n\n[What this project is about at the intersection of the research question, hypotheses, and grounding sources]\n\n"
        "## Participant POV\n\n"
        "Scores: 0 = extremely relevant | 1 = relevant | 2 = ambiguous | 3 = not relevant | 4 = counterproductive\n\n"
        "### Customer\n\n### Problem\n\n### Solution\n\n"
        "## Researcher POV\n\n"
        "> Edit this section to course-correct AI interpretation. Defaults to NA (ignored by system).\n\n"
        "### On-topic\nNA\n\n### Interesting\nNA\n\n### Off-topic\nNA\n"
    ),
    "definitions.md": (
        "# Definitions & Key Concepts\n\n"
        "> Add term definitions here when precise meaning matters for analysis.\n\n"
        "| Term | Definition |\n|---|---|\n| example term | What it means in this study's context |\n"
    ),
    "sample_analysis.md": (
        "# Sample Analysis\n\n"
        "> Optional. Paste a researcher-annotated example transcript excerpt here with notes\n"
        "> on how to interpret it. The AI will use this as a style and interpretation reference.\n\n"
    ),
    "memos.md": (
        "# Memos & Team Notes\n\n"
        "> Paste backchannel chat, meeting notes, debrief notes, or emails here.\n"
        "> The AI reads this file during grounding analysis to understand what the team found significant.\n\n"
    ),
}


def scaffold_config(
    project_dir: str,
    title: str,
    description: str,
    research_question: str,
    hypotheses: list[str],
    participants: list[dict[str, str]],
    method: str = "Semi-structured interview",
    max_iterations: int = 3,
    motivations: str = "",
    goals: str = "",
    intended_impacts: str = "",
) -> dict[str, Any]:
    """Create a research_config.yaml for a new study, plus grounding/ stubs."""
    project_path = Path(project_dir).resolve()
    project_path.mkdir(parents=True, exist_ok=True)

    study_section: dict[str, Any] = {
        "title": title,
        "description": description,
        "method": method,
    }
    if motivations:
        study_section["motivations"] = motivations
    if goals:
        study_section["goals"] = goals
    if intended_impacts:
        study_section["intended_impacts"] = intended_impacts

    config = {
        "study": study_section,
        "research": {
            "question": research_question,
            "hypotheses": hypotheses,
        },
        "grounding": {
            "additional_context": "",
        },
        "participants": participants,
        "transcripts_dir": "./transcripts",
        "output": {
            "dir": "./output",
            "max_iterations": max_iterations,
        },
    }

    config_path = project_path / "research_config.yaml"
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    (project_path / "transcripts").mkdir(exist_ok=True)
    (project_path / "output").mkdir(exist_ok=True)

    grounding_path = project_path / "grounding"
    grounding_path.mkdir(exist_ok=True)
    (grounding_path / "working").mkdir(exist_ok=True)
    for stub_name, stub_content in _GROUNDING_STUBS.items():
        stub_file = grounding_path / stub_name
        if not stub_file.exists():
            stub_file.write_text(stub_content, encoding="utf-8")

    return {"config_path": str(config_path), "status": "created", "grounding_dir": str(grounding_path)}


def load_config_tool(config_path: str) -> dict[str, Any]:
    """Load and validate config."""
    return load_config(config_path)


def preflight_check(config_path: str) -> dict[str, Any]:
    """Validate project readiness."""
    config = load_config(config_path)
    if "error" in config:
        return config

    issues: list[str] = []
    project_dir = get_project_dir(config)
    transcripts_dir = get_transcripts_dir(config)
    output_dir = get_output_dir(config)

    if not transcripts_dir.exists():
        issues.append(f"Transcripts dir not found: {transcripts_dir}")

    for p in config.get("participants", []):
        f = transcripts_dir / p["file"]
        if not f.exists():
            issues.append(f"Transcript not found for {p['id']}: {f}")

    output_dir.mkdir(parents=True, exist_ok=True)

    if issues:
        return {"ready": False, "issues": issues}
    return {"ready": True, "participants": len(config["participants"])}


def get_project_status(config_path: str) -> dict[str, Any]:
    """Return per-participant pipeline state summary."""
    config = load_config(config_path)
    if "error" in config:
        return config

    output_dir = get_output_dir(config)
    state = PipelineState(output_dir)
    all_states = state.get_all_states()

    participants_status = []
    for p in config.get("participants", []):
        pid = p["id"]
        pstate = all_states.get(pid, {})
        participants_status.append({
            "id": pid,
            "state": pstate.get("state", "not_started"),
            "iteration": pstate.get("iteration", 0),
            "locked_count": pstate.get("locked_count", 0),
        })

    return {"participants": participants_status}
